//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ax2012WCFService.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Ax2012DependenciesEntities : DbContext
    {
        public Ax2012DependenciesEntities()
            : base("name=Ax2012DependenciesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spExtractAxPaymentTerms_Result> spExtractAxPaymentTerms(string dataAreaId)
        {
            var dataAreaIdParameter = dataAreaId != null ?
                new ObjectParameter("DataAreaId", dataAreaId) :
                new ObjectParameter("DataAreaId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spExtractAxPaymentTerms_Result>("spExtractAxPaymentTerms", dataAreaIdParameter);
        }
    }
}
